services:
  mongodb:
    image: mongo:latest
    container_name: market_mongo
    ports:
      - 27017:27017
    volumes:
      - /Users/jjh/data/marketMongoDb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
